# Workflow for rendering R Markdown files and deploying to GitHub Pages
name: render-rmarkdown-pages
on:
  push:
    paths: ['**.Rmd']
  schedule:
    # Runs at 5 PM PDT (UTC-7) which is midnight UTC-0
    - cron: '0 0 * * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Render Rmarkdown files
        run: |
          mkdir -p _site
          if [ "${{ github.event_name }}" == "push" ]; then
            # For push events, only render changed files
            RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
          else
            # For scheduled events, render all Rmd files
            RMD_PATH=($(find . -name '*.Rmd'))
          fi
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f, output_dir = "_site")' ${RMD_PATH[*]}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
